name: time_pomodoro
version: 1.0.0+1
publish_to: none
description: A flutter pomodoro Timer app.
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.0.0+2
  flutter_svg: ^0.22.0
  font_awesome_flutter: ^9.1.0
  get: 4.3.8
  google_fonts: ^2.1.0
  lottie: ^1.1.0
  mouse_parallax: ^1.1.0
  syncfusion_flutter_gauges: ^19.2.59
  url_launcher: ^6.0.9
  flutter:
    sdk: flutter

dev_dependencies:
  lint: 1.6.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/svg/.

  uses-material-design: true
