name: time_pomodoro
version: 1.0.0+1
publish_to: none
description: A flutter pomodoro Timer app.
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  google_fonts: 2.1.0
  flutter_screenutil: 5.0.0+2
  get: 4.3.8
  flutter:
    sdk: flutter

dev_dependencies:
  lint: 1.6.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
